Drawers:
  Global:
    Grids:
    DefaultGeo:
      MaxDepth: 3
  Event:
    VertexCamera:
    LinearTraj:
    EDepDEdx:
      dEdxScale:
        min: 0.
        max: 8.
Services:
  Geo:
    fiducial: "volWorld"
